language: python
before_install:
    - pip3 install --only-binary=numpy,pandas numpy pandas
    - pip3 install sphinx
    - pip3 install coveralls
python:
    - 3.5
    - 3.6
install: 
    - pip3 install --prefix=~/.local .
script: 
    - coverage run --source=netatmo setup.py test
after_success:
    - coveralls
