language: python
before_install:
    - "pip3 install --only-binary=numpy,pandas numpy pandas"
python:
    - "3.5"
    - "3.6"
    - "nightly"
install: "pip3 install --prefix=~/.local ."
script: ./setup.py test
